config/routes.rb
Rails.application.routes.draw do
  root to:'projects#animation'
  devise_for :users, controllers: { registrations: "registrations"}
  get 'sign_me_out', to: 'application#sign_me_out'

  ## Admin control panel routes
  # Actions/routes concerning the Project model
  get '/admin', to: 'administrator#admin_projects_index' #Used as a shortcut for logging into the app
  get '/admin/projects', to: 'administrator#admin_projects_index', as: 'admin_projects_index'
  get '/admin/archives', to: 'administrator#admin_archives_index', as: 'admin_archives_index'
  get '/admin/projects/:id/edit', to: 'administrator#edit_project', as: 'edit_project'
  put '/admin/projects/:id', to: 'administrator#update_project', as: 'update_project'
  get '/admin/projects/new', to: 'administrator#new_project', as: 'new_project'
  post '/admin/projects', to: 'administrator#create_project'
  get '/admin/projects/:id/archiver', to: 'administrator#archive_project', as: 'archive_project'
  get '/admin/archives/:id/unarchiver', to: 'administrator#unarchive_project', as: 'unarchive_project'
  delete '/admin/projects/:id', to: 'administrator#delete_project', as: 'delete_project'
  # Actions/routes concerning the Image model
  get '/admin/projects/:id/edit/set_cover_image', to: 'administrator#set_cover_image', as: 'set_cover_image'
  delete '/admin/projects/:id/edit/delete_image', to: 'administrator#delete_project_image', as: 'delete_image'
  # Actions/routes concerning the Information model
  get '/admin/information/:id/edit', to: 'administrator#edit_information', as: 'edit_information'
  put '/admin/information/:id', to: 'administrator#update_information', as: 'update_information'
  # Actions/routes concerning the Footer model
  get '/admin/footer/:id/edit', to: 'administrator#edit_footer', as: 'edit_footer'
  put '/admin/footer/:id', to: 'administrator#update_footer', as: 'update_footer'

  # Frontend routes
  get 'information', to: 'pages#information'
  get 'featured', to: 'projects#index'
  resource :archive, only: [:show]
  resources :projects, only: [:index, :show], path: "featured"
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :ordered, -> { where(visibility: true).order(:project_order) }

  has_many :images
  has_many :photos, -> {photo}, class_name: "Image"
  has_many :portrait_photos, -> {photo.portrait}, class_name: "Image"
  has_many :landscape_photos, -> {photo.landscape}, class_name: "Image"
  has_many :prints, -> {printable}, class_name: "Image"
  has_many :videostills, -> {videostill}, class_name: "Image"

  def next
    self.class.ordered.where("project_order > ? AND visibility = true", project_order).first
  end

  def previous
    self.class.ordered.where("project_order < ? AND visibility = true", project_order).last
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.ordered
    set_title
  end

  def show
    @project = Project.friendly.find(params[:id])
    set_title
    # Sort images by numerical order
    photos = @project.images.select{ |img| img.coverimage != true }.sort_by { |img| img.filename }

    # generate hash
    filenames = photos.each.map(&:filename)
    formats = photos.each.map(&:format)
    image_hash = Hash[filenames.zip(formats)]

    @images = []
    # Loop through hash
    image_hash.each_with_index do |(hash_filename, format), index|
      # Skip the current element if the filename in the hash includes 'skip'
      next if format.match(/__skip_photo__/)
      # Loop through photos array within the hash iteration
      photos.each_with_index do |photo_object, index|
        # If the img is landscape then place it directly in the array
        @images << [photo_object] if format != "portrait" && photo_object.filename == hash_filename
        # Build an array of the image and its sibling if its a portrait format
        if format == "portrait" && photo_object.filename == hash_filename
          # Display 1 portrait photo
          if photos[index+1] == nil
            # Generate an array of two portrait photos and place in images array
            @images << [photo_object, photos[index+1]]
            # save the next portrait image file as a variable
            next_image = photos[index+1].filename unless next_image.nil?
            # prepend next portrait iamge variable in the original hash with '__skip_photo__'
            image_hash[next_image] = "__skip_photo__" + image_hash[next_image] unless next_image.nil?
          else
            # Generate an array of two portrait photos and place in images array
            @images << [photo_object, photos[index+1]]
            # save the next portrait image file as a variable
            next_image = photos[index+1].filename #unless next_image.nil?
            # prepend next portrait iamge variable in the original hash with '__skip_photo__'
            image_hash[next_image] = "__skip_photo__" + image_hash[next_image] #unless next_image.nil?
          end
        end
      end
    end
  end

  private

  def set_title
    @title = "| Featured" if @projects.present?
    @title = "| #{@project.name}" if @project.present?
  end

  def portrait_photos

  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/animation.html.erb
<div id="_3d-container"></div>

app/views/projects/index.html.erb
<b-container >
<% @projects.sort_by(&:project_order).reverse_each do |project| %>
  <b-row class="pt-4">
    <b-col sm="12" >
      <div class="client-featured-card">
        <%=link_to(project_path(project.slug)) do %>
          <img src="<%= project.images.select(&:coverimage).first.url unless project.images.first.nil? %>" alt="<%= project.name unless project.name.nil?%>">
        <% end %>
        <div class="project-info">
          <span class="name"><%= project.name.upcase %></span>
          <span class="description"><%= project.blurb %></span>
        </div>
      </div>
    </b-col>
  </b-row>
<% end %>
</b-container>

app/views/projects/old_show.html.erb
<b-container >
  <%-@project.portrait_photos.each_slice(2) do |group|%>
    <b-form-row class="justify-content-md-center">
      <%-group.each do |portrait_photo|%>
        <b-col sm="12" md="5">
          <b-img src="<%=cl_image_path portrait_photo.url%>" alt="<%="#{portrait_photo.url.split('_').first}"%>" fluid></b-img>
        </b-col>
      <%end%>
    </b-form-row>
  <%end%>
  <b-form-row>
    <%-@project.landscape_photos.each do |landscape_photo|%>
      <b-col sm="12" md="10" offset-md="1">
        <b-img src="<%=cl_image_path landscape_photo.url%>" alt="<%="#{landscape_photo.url.split('_').first}"%>" fluid></b-img>
      </b-col>
    <%end%>
  </b-form-row>
  <b-form-row>
    <%-@project.prints.each do |print|%>
      <b-col sm="12" md="10" offset-md="1">
        <b-img src="<%=cl_image_path print.url%>" alt="<%="#{print.url.split('_').first}"%>" fluid></b-img>
      </b-col>
    <%end%>
  </b-form-row>
  <b-form-row>
    <%-@project.videostills.each do |videostill|%>
      <b-col sm="12" md="10" offset-md="1">
        <b-img src="<%=cl_image_path videostill.url%>" alt="<%="#{videostill.url.split('_').first}"%>" fluid></b-img>
      </b-col>
    <%end%>
  </b-form-row>
  <b-form-row>
    <b-col sm="12" md="10" offset-md="1">
      <b-form-row>
        <b-col cols="6" offset="6">
          <div class="description float-right">
            <%= simple_format @project.description %>
          </div>
        </b-col>
      </b-form-row>
    </b-col>
  </b-form-row>
  <div class="pagination">
    <%=@project.previous.nil? ? raw("<span></span>") : link_to("⟵", project_path(@project.previous))%>
    <%=@project.next.nil? ? raw("<span></span>") : link_to("⟶", project_path(@project.next))%>
  </div>
</b-container>

app/views/projects/show.html.erb
<b-container >
  <% @images.each do |img| %>
  <% #byebug %>
    <!-- Controller outputs array of images; portrait photos are are x2 array within the image array -->
    <% if img.size >= 2 %>
      <b-form-row class="justify-content-md-center">
        <% img.each do |portrait_photo|%>
          <b-col sm="12" md="5">
            <b-img src="<%=cl_image_path portrait_photo.url unless portrait_photo.nil? %>" alt="<%="#{portrait_photo.url.split('/').last}" unless portrait_photo.nil? %>" fluid></b-img>
          </b-col>
        <% end %>
      </b-form-row>
    <% end %>
    <!-- Controller prints non-portrait photos (landscape, videostills etc) -->
    <% if img.size < 2 %>
      <b-form-row>
        <b-col sm="12" md="10" offset-md="1">
          <b-img src="<%=cl_image_path img.first.url%>" alt="<%="#{img.first.url.split('/').last}"%>" fluid></b-img>
        </b-col>
      </b-form-row>
    <% end %>
  <% end %>

  <!-- Project description -->
  <b-form-row>
    <b-col sm="12" md="10" offset-md="1">
      <b-form-row>
        <b-col cols="6" offset="6">
          <div class="description float-right">
            <%= simple_format @project.description %>
          </div>
        </b-col>
      </b-form-row>
    </b-col>
  </b-form-row>

  <!-- Pagination -->
  <div class="pagination">
    <%=@project.previous.nil? ? raw("<span></span>") : link_to("⟵", project_path(@project.previous))%>
    <%=@project.next.nil? ? raw("<span></span>") : link_to("⟶", project_path(@project.next))%>
  </div>
</b-container>